### ISSUE TITLE
Unable to add JAVA_OPTS due setting in entrypoint.sh

### ISSUE THREAD

**Issue by JohanHolman** [ivantichy/jira-docker#20]
To be able to add extra Java options like http.proxyHost, -Dhttp.proxyPort, etc. I suggest to update entrypoint.sh and change the line
export JAVA_OPTS=-Djava.net.preferIPv4Stack=true
into
export JAVA_OPTS="-Djava.net.preferIPv4Stack=true $JAVA_OPTS"

**Comment by ivantichy** [comment]
fixed imho :)
